# Generated by Django 5.2.8 on 2025-11-25 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField()),
                ('current_question_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_center.cluster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_center.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cluster', 'subject', 'attempt')},
            },
        ),
    ]
