# Generated by Django 5.2.8 on 2025-11-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_center', '0002_remove_testresult_cluster_testresult_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_center.cluster'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_center.subject'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
