# Generated by Django 5.2.8 on 2025-11-23 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_center', '0003_testresult_cluster_alter_testresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_center.cluster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_center.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total',
            field=models.IntegerField(),
        ),
    ]
